language: node_js
node_js:
  - node
branches:
  only:
    - master
    - feature/travis_test

deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: feature/travis_test